server {
    listen 80;
    
    resolver 127.0.0.11 valid=30s;
    
    location /api/ {
        proxy_pass http://thesis-validator.railway.internal:8080/api/;
    }
    
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}